#!/bin/bash

# Uninstall icons for TML and Rubble files.
# simple utility, no arg checks
#icon_theme_root=$1


echo "*** This script will not clean index.themes!!! ***"

#icon_theme_root=/usr/share/icons/hicolor
#icon_theme_root=/usr/share/icons/gnome
#icon_theme_root=/usr/share/icons/Adwaita
icon_theme_root=/usr/share/icons/Mint-Y

#! Dont remove folders or configuration

# Delete icons
rm $icon_theme_root/scalable/mimetypes/text-x-rubble.svg 
rm $icon_theme_root/scalable/mimetypes/text-x-tml.svg 

echo "Update cache: $icon_theme_root"
gtk-update-icon-cache $icon_theme_root

echo "done"
