#!/bin/bash

# Uninstall icons for TML and Rubble files.
# simple utility, no arg checks
#icon_theme_root=$1

echo "*** Dont run multiple times!!! ***"
echo "*** This script canot clean index.theme ***"

# Add Icon
#icon_theme_root=/usr/share/icons/hicolor 
#icon_theme_root=/usr/share/icons/gnome
#icon_theme_root=/usr/share/icons/Adwaita
icon_theme_root=/usr/share/icons/Mint-Y
echo "= Install Icon"

## Modify index.theme
echo "Modify Config: $icon_theme_root/index.theme"

mkdir -p $icon_theme_root/scalable/mimetypes

## add to directories entry
sed -i 's/Directories=/Directories=scalable\/mimetypes,/' $icon_theme_root/index.theme

## add stanza to end
echo "
###################

[scalable/mimetypes]
Size=16
Context=Mimetypes
Type=Scalable
MinSize=8
MaxSize=512
" >> $icon_theme_root/index.theme


## Install icons
echo "Install icon: $icon_theme_root/scalable/mimetypes/text-x-rubble.svg"

# hicolor scalable/mimetypes is basic Size=128
# size seems to be ignored on scalable, and Gnone is happy with and 
# configures 16x16
cp ./16/text-x-rubble.svg $icon_theme_root/scalable/mimetypes
cp ./32/text-x-tml.svg $icon_theme_root/scalable/mimetypes

## Update icon cache
echo "Update cache: $icon_theme_root"
gtk-update-icon-cache $icon_theme_root

echo "done (may require file browser refresh))"
