#!/bin/bash

# Install mimetypes for TML and Rubble files.
mime_register_root=~/.local/share/mime
echo "= Install File Mimes for TML and Rubble"
echo "assumes a local config destination $mime_register_root"

## check if a directory exists
if [ ! -d "$mime_register_root" ]; then
    (>&2 echo "The directory '$mime_register_root' does not exist"); 
    exit 1;
fi

## Append config
echo "Create config: $mime_register_root/packages/rubble.xml"
echo '<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="text/x-rubble">
    <sub-class-of type="text/plain"/>
    <glob pattern="*.rbl"/>
  </mime-type>
</mime-info>' >  $mime_register_root/packages/rubble.xml

echo '<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="text/x-tml">
    <sub-class-of type="text/plain"/>
    <glob pattern="*.tml"/>
    <magic>
        <match type="string" offset="0" value="= "/>
    </magic>
  </mime-type>
</mime-info>' >  $mime_register_root/packages/tml.xml

## Update mime cache
echo "Update cacbhe: $mime_register_root"
update-mime-database $mime_register_root
