#!/bin/bash

# Install Gedit config for TML files.
# simple utility, no arg checks

echo "*** Install ***"
echo "assumes a local config destination ~/.local/share/gtksourceview-3.0/"
xdg_config_path=~/.local/share/gtksourceview-3.0/

## check if a directory exists
if [ ! -d "$xdg_config_path" ]; then
    (>&2 echo "The directory '$xdg_config_path' does not exist"); 
    exit 1;
fi
cp tml.lang $xdg_config_path/language-specs/
echo "restart xed"
